config/routes.rb
Rails.application.routes.draw do
  resources :simulators

  resources :subjects

  # You can have the root of your site routed with "root"
  root 'application#hello'
end

app/models/simulator.rb
class Simulator < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end
end

app/controllers/simulators_controller.rb
class SimulatorsController < ApplicationController
  before_action :set_simulator, only: [:show, :edit, :update, :destroy]

  # GET /simulators
  # GET /simulators.json
  def index
    @simulators = Simulator.all
  end

  # GET /simulators/1
  # GET /simulators/1.json
  def show
  end

  # GET /simulators/new
  def new
    @simulator = Simulator.new
  end

  # GET /simulators/1/edit
  def edit
  end

  # POST /simulators
  # POST /simulators.json
  def create
    @simulator = Simulator.new(simulator_params)

    respond_to do |format|
      if @simulator.save
        format.html { redirect_to @simulator, notice: 'Simulator was successfully created.' }
        format.json { render :show, status: :created, location: @simulator }
      else
        format.html { render :new }
        format.json { render json: @simulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulators/1
  # PATCH/PUT /simulators/1.json
  def update
    respond_to do |format|
      if @simulator.update(simulator_params)
        format.html { redirect_to @simulator, notice: 'Simulator was successfully updated.' }
        format.json { render :show, status: :ok, location: @simulator }
      else
        format.html { render :edit }
        format.json { render json: @simulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulators/1
  # DELETE /simulators/1.json
  def destroy
    @simulator.destroy
    respond_to do |format|
      format.html { redirect_to simulators_url, notice: 'Simulator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simulator
      @simulator = Simulator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulator_params
      params.require(:simulator).permit(:id, :name, :url)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simulators_helper.rb
module SimulatorsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GabrielTp3T2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/simulators/_form.html.erb
<%= form_for(@simulator) do |f| %>
  <% if @simulator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simulator.errors.count, "error") %> prohibited this simulator from being saved:</h2>

      <ul>
      <% @simulator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simulators/edit.html.erb
<h1>Editing Simulator</h1>

<%= render 'form' %>

<%= link_to 'Show', @simulator %> |
<%= link_to 'Back', simulators_path %>

app/views/simulators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Simulators</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simulators.each do |simulator| %>
      <tr>
        <td><%= simulator.id %></td>
        <td><%= simulator.name %></td>
        <td><%= simulator.url %></td>
        <td><%= link_to 'Show', simulator %></td>
        <td><%= link_to 'Edit', edit_simulator_path(simulator) %></td>
        <td><%= link_to 'Destroy', simulator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simulator', new_simulator_path %>

app/views/simulators/new.html.erb
<h1>New Simulator</h1>

<%= render 'form' %>

<%= link_to 'Back', simulators_path %>

app/views/simulators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @simulator.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @simulator.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @simulator.url %>
</p>

<%= link_to 'Edit', edit_simulator_path(@simulator) %> |
<%= link_to 'Back', simulators_path %>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @subject.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>